### PR TITLE
Added some fix & improvement

### PR DESCRIPTION
**Pull request by Fro99666**
i didnt made the .min of the JS as you didn't answered me wich minizer you use

### CODE REVIEW

**Comment by simogeo** [comment]
One more thing, there is a  alignment  bug in chrome with your version when the file name is long, see screenshot below : 

align-bug

Any idea of what could cause this ?

**Comment by Fro99666** [comment]
nothing i commited could explain this, did you tried to use Shift + F5 to refresh without cache ?

**Comment by simogeo** [comment]
Ok, forget this issue, I'll fix this later (see new reference #367)

**Comment by simogeo** [comment]
alignment bug is fixed : 56d7879cecde5a6c01b8e22721ef691f520775ce

**Comment by Fro99666** [comment]
sorry weather is too hot to work, i ll be back soon to do the request !

**Comment by simogeo** [comment]
it's getting cold right now ;-)

**Comment by Fro99666** [comment]
can you remember what s left to do from this commits ? thanks

**Comment by simogeo** [comment]
Do separate PR. See https://github.com/simogeo/Filemanager/pull/366#commitcomment-11860767

The most important demand from me would be to separate PDF viewer commit from other formats (reader). see also [this comment](https://github.com/simogeo/Filemanager/pull/366#commitcomment-11856906)

**Comment by Fro99666** [comment]
i removed embed stuff as it look like to not pleased you, about the multiples request, i checked about it, i would have to make separate branches with change in each. So to prevent useless work, if there something you don't need, tell me and i remove it from request.

**Comment by simogeo** [comment]
Just PR PDFViewer and your Purple theme (distinctly)

I will handle manually other proposed fixes !

**Comment by Fro99666** [comment]
ok ! incoming ;)

**Comment by Fro99666** [comment]
ok, i repost the request, so i close this one

**Pull request closed without merging**
