### PR TITLE
Update de.js

### PR DESCRIPTION
**Pull request by robsch**
Translated mising texts and improved some other texts. Is that okay?

### CODE REVIEW

**Comment by simogeo** [comment]
I guess so ;-)  
Many thanks for German users

**Comment by robsch** [comment]
That was my first commit on github! I wasn't sure if I'm doing thing right.

**Comment by simogeo** [comment]
You did well and I suggest you to commit even more ;-) 

Very proud your first github interaction was for this project !

**Comment by robsch** [comment]
Haha, your welcome! ;-)

**Pull request merged**
