### PR TITLE
Update filemanager.js

### PR DESCRIPTION
**Pull request by bestmomo**
Set language where there is also country code, for example *pt-BR*.

### CODE REVIEW

**Comment by simogeo** [comment]
thanks, I'll provide now the minified version

**Comment by simogeo** [comment]
well, well, actually the way it works now supports both language and language / country codes.
See provided files here : https://github.com/simogeo/Filemanager/tree/master/scripts/languages

**Comment by bestmomo** [comment]
Humm.. right. But for my example with *pt-Br* that doesn't exists, should be great to fall down on *pt* rather than default *en*.

**Comment by simogeo** [comment]
in that case, could you propose an other fix with fall down logic !? (also to apply on the php side)

**Comment by bestmomo** [comment]
In this case just adding some logic :
```
if($.urlParam('langCode') != 0) {
	if(file_exists ('scripts/languages/'  + $.urlParam('langCode') + '.js')) {
		config.options.culture = $.urlParam('langCode');
	} else {
		var urlLang = $.urlParam('langCode').substring(0, 2);
		if(file_exists ('scripts/languages/'  + urlLang + '.js')) config.options.culture = urlLang;
	}
}
```

**Comment by simogeo** [comment]
thanks @bestmomo. See last commit

**Comment by bestmomo** [comment]
Thanks

**Pull request closed without merging**
