### PR TITLE
Change duplicate y-acute to y-grave

### PR DESCRIPTION
**Pull request by phil-davis**
My IDE told me about this - y-acute is duplicated here. Probably should be y-grave.
Noticed in Mautic - PR https://github.com/mautic/mautic/pull/4999

### CODE REVIEW

**Comment by phil-davis** [comment]
Is there any "upstream" of this code somewhere now that this repo is deprecated?

**Comment by simogeo** [comment]
you can also update [RichFilemanager](https://github.com/servocoder/RichFilemanager)

**Comment by phil-davis** [comment]
RichFilemanager seems to have a different ``cleanString`` that is used by ``cleanFileName`` and ``cleanFileNameDefault`` and those only substitute a few characters. So I do not see a place where this fix [can|needs to be] applied.
https://github.com/servocoder/RichFilemanager/blob/master/connectors/jsp/libraries/java/src/edu/fuberlin/AbstractFM.java

**Comment by simogeo** [comment]
You're probably right, and @servocoder will confirm this, I guess.

**Comment by psolom** [comment]
Yeah, it was reworked in RichFilemanager, don't bother yourself with that.
@simogeo thanks for the reference to RFM

**Pull request merged**
